"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[8125],{53304:(e,n,s)=>{s.r(n),s.d(n,{assets:()=>l,contentTitle:()=>o,default:()=>h,frontMatter:()=>r,metadata:()=>c,toc:()=>u});var t=s(74848),i=s(28453);const r={title:"1.24.4"},o=void 0,c={id:"release-notes/1.24.4",title:"1.24.4",description:"General",source:"@site/../docs/release-notes/1.24.4.md",sourceDirName:"release-notes",slug:"/release-notes/1.24.4",permalink:"/documentation/release-notes/1.24.4",draft:!1,unlisted:!1,editUrl:"https://github.com/rucio/documentation/tree/main/docs/../docs/release-notes/1.24.4.md",tags:[],version:"current",frontMatter:{title:"1.24.4"}},l={},u=[{value:"General",id:"general",level:2},{value:"Enhancements",id:"enhancements",level:3},{value:"Bugs",id:"bugs",level:3}];function a(e){const n={a:"a",h2:"h2",h3:"h3",li:"li",ul:"ul",...(0,i.R)(),...e.components};return(0,t.jsxs)(t.Fragment,{children:[(0,t.jsx)(n.h2,{id:"general",children:"General"}),"\n",(0,t.jsx)(n.h3,{id:"enhancements",children:"Enhancements"}),"\n",(0,t.jsxs)(n.ul,{children:["\n",(0,t.jsxs)(n.li,{children:["Core & Internals: Problem with config endpoint ",(0,t.jsx)(n.a,{href:"https://github.com/rucio/rucio/issues/3916",children:"#3916"})]}),"\n",(0,t.jsxs)(n.li,{children:["Documentation: cli-admin example not running ",(0,t.jsx)(n.a,{href:"https://github.com/rucio/rucio/issues/4315",children:"#4315"})]}),"\n",(0,t.jsxs)(n.li,{children:["Documentation: Fix small typos and grammatical errors ",(0,t.jsx)(n.a,{href:"https://github.com/rucio/rucio/issues/4321",children:"#4321"})]}),"\n",(0,t.jsxs)(n.li,{children:["Documentation: Fix typos in replica_workflow.rst ",(0,t.jsx)(n.a,{href:"https://github.com/rucio/rucio/issues/4324",children:"#4324"})]}),"\n",(0,t.jsxs)(n.li,{children:["REST & API: OIDC authentication endpoint on Flask ",(0,t.jsx)(n.a,{href:"https://github.com/rucio/rucio/issues/4042",children:"#4042"})]}),"\n"]}),"\n",(0,t.jsx)(n.h3,{id:"bugs",children:"Bugs"}),"\n",(0,t.jsxs)(n.ul,{children:["\n",(0,t.jsxs)(n.li,{children:["Core & Internals: lfns2pfns in rsemanager throws ORM exception when no replica can be found ",(0,t.jsx)(n.a,{href:"https://github.com/rucio/rucio/issues/4311",children:"#4311"})]}),"\n",(0,t.jsxs)(n.li,{children:["Deletion: RSE sorting in reaper2 failing if there is no obsolete rse usage source ",(0,t.jsx)(n.a,{href:"https://github.com/rucio/rucio/issues/4307",children:"#4307"})]}),"\n"]})]})}function h(e={}){const{wrapper:n}={...(0,i.R)(),...e.components};return n?(0,t.jsx)(n,{...e,children:(0,t.jsx)(a,{...e})}):a(e)}},28453:(e,n,s)=>{s.d(n,{R:()=>o,x:()=>c});var t=s(96540);const i={},r=t.createContext(i);function o(e){const n=t.useContext(r);return t.useMemo((function(){return"function"==typeof e?e(n):{...n,...e}}),[n,e])}function c(e){let n;return n=e.disableParentContext?"function"==typeof e.components?e.components(i):e.components||i:o(e.components),t.createElement(r.Provider,{value:n},e.children)}}}]);